# fly.toml app configuration file generated for rabbitinflux on 2025-12-17T21:40:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brokwe"

primary_region = "sin"

[build]
  image = "rabbitmq:3.13-management"

[[services]]
  internal_port = 5672
  protocol = "tcp"

  [[services.ports]]
    port = 5672

[[services]]
  internal_port = 15672
  protocol = "tcp"

  [[services.ports]]
    port = 15672

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 15672